version: '3.9'

services:
  nginx:
    image: docker.io/library/nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    network_mode: "host"
    restart: always

  rosblox-studio:
    image: ghcr.io/rosblox/studio:latest
    volumes:
      - ./studio/layout.json:/src/layout.json
    ports:
      - 8080:8080
    restart: always

  ros-rosbridge-suite:
    image: ghcr.io/rosblox/ros-rosbridge-suite:humble
    ports:
      - 9090:9090
    restart: always
    command: ros2 launch rosbridge_server rosbridge_websocket_launch.xml

  ros-ros1-bridge:
    image: ros:foxy-ros1-bridge
    restart: always
    environment:
      - ROS_MASTER_URI=http://ros-loam-livox:11311
      - ROS_HOSTNAME=ros-ros1-bridge
    command: ros2 run ros1_bridge dynamic_bridge --bridge-all-1to2-topics

  ros-loam-livox:
    image: ghcr.io/rosblox/ros-loam-livox:melodic
    restart: always
    command: roslaunch loam_livox livox.launch rviz:=false
    environment:
      - ROS_HOSTNAME=ros-loam-livox
